insert into sight (ticketprice, Weblink, destinationid) values (231, 'www.EifelTower.com', 2);
insert into sight (ticketprice, Weblink, destinationid) values (85, 'www.NotreDameCathedral.com', 36);
insert into sight (ticketprice, Weblink, destinationid) values (154, 'www.VieuxPort.com', 12);
insert into sight (ticketprice, Weblink, destinationid) values (28, 'www.VieuxLyon.com', 65);
insert into sight (ticketprice, Weblink, destinationid) values (71, 'www.PetiteFrancedistrict.com', 37);
insert into sight (ticketprice, Weblink, destinationid) values (231, 'www.Romanamphitheatre.com', 87);
insert into sight (ticketprice, Weblink, destinationid) values (214, 'www.BeauxArtsmuseum.com', 66);
insert into sight (ticketprice, Weblink, destinationid) values (170, 'www.CrockerArtMuseuem.com', 45);
insert into sight (ticketprice, Weblink, destinationid) values (153, 'www.ElPasoMuseumofArt.com', 80);
insert into sight (ticketprice, Weblink, destinationid) values (30, 'www.TimesSquare.com', 86);
insert into sight (ticketprice, Weblink, destinationid) values (173, 'www.HouseofbluesDallas.com', 8);
insert into sight (ticketprice, Weblink, destinationid) values (248, 'www.ConnecticutRiverWalk.com', 9);
insert into sight (ticketprice, Weblink, destinationid) values (236, 'www.StonestownGalleria.com', 19);
insert into sight (ticketprice, Weblink, destinationid) values (140, 'www.FaneuilHall.com', 58);
insert into sight (ticketprice, Weblink, destinationid) values (291, 'www.MuseumoftheAmericanGI.com', 34);
insert into sight (ticketprice, Weblink, destinationid) values (83, 'www.ArtInstituteofChicago.com', 48);
insert into sight (ticketprice, Weblink, destinationid) values (141, 'www.Muncie.com', 93);
insert into sight (ticketprice, Weblink, destinationid) values (133, 'www.RedFort.com', 57);
insert into sight (ticketprice, Weblink, destinationid) values (163, 'www.FalaknumaPalace.com',46);
insert into sight (ticketprice, Weblink, destinationid) values (244, 'www.SevenTombs.com', 75);
insert into sight (ticketprice, Weblink, destinationid) values (293, 'www.SalarjungMuseuem.com', 24);
insert into sight (ticketprice, Weblink, destinationid) values (249, 'www.GreatWallofChina.com', 17);

select * from sight;