insert into waysoftravel (destinationid, waytravel) values 
(2, 'bus, train, car, plane'),
(3, 'train, car, plane'), 
(5, 'train, car, plane'),
(7, 'bus, car, plane'),
(8, 'bus, train, car, plane'),
(9, 'bus, train, car, plane'),
(12, 'bus, train, car, plane'),
(16, 'train, plane'),
(17, 'car, plane'),
(18, 'car, plane'),
(19, 'bus, train, car'),
(21, 'bus, train, car'),
(24, 'bus, train, car'),
(25, 'bus, train, plane'),
(26, 'bus, train, plane'),
(27, 'bus, train, car, plane'),
(34, 'bus'),
(36, 'train, car, plane'),
(37, 'train'),
(40, 'bus'),
(41, 'bus'),
(45, 'plane'),
(46, 'plane'),
(48, 'plane'),
(52, 'train, plane'),
(57, 'car'),
(58, 'bus, car'),
(62, 'bus, car'),
(65, 'bus, car'),
(66, 'bus, plane'),
(75, 'plane'),
(78, 'bus'),
(80, 'bus'),
(86, 'car'),
(87, 'bus, train, car, plane'),
(90, 'bus, train, car, plane'),
(93, 'bus, train, car, plane'),
(95, 'bus, train, car, plane'),
(96, 'bus, train, car, plane'),
(98, 'bus, train, car, plane');

select * from waysoftravel;

